# Generated by Django 5.2.16 on 2026-07-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("read", "read"),
                            ("feed", "feed"),
                            ("drift", "drift"),
                            ("sync", "sync"),
                            ("auth_denied", "auth_denied"),
                            ("settings_change", "settings_change"),
                            ("degraded", "degraded"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("entity_ids", models.JSONField(blank=True, default=list)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="api_keys.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["type", "created_at"],
                        name="events_even_type_e33440_idx",
                    )
                ],
            },
        ),
    ]
