# Generated by Django 5.2.16 on 2026-07-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SdkOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("test_connection", "test_connection"),
                            ("feed_extraction", "feed_extraction"),
                            ("assemble_context", "assemble_context"),
                            ("chat", "chat"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=64)),
                ("ok", models.BooleanField(blank=True, null=True)),
                (
                    "error_class",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("input_tokens", models.BigIntegerField(blank=True, null=True)),
                ("output_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_read_tokens", models.BigIntegerField(blank=True, null=True)),
                ("cache_write_tokens", models.BigIntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("num_turns", models.IntegerField(blank=True, null=True)),
                (
                    "prompt_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("subject_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "subject_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "created_at"],
                        name="events_sdko_kind_7aeef0_idx",
                    )
                ],
            },
        ),
    ]
