# Generated by Django 5.2.16 on 2026-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_sdkoperation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("read", "read"),
                    ("feed", "feed"),
                    ("drift", "drift"),
                    ("sync", "sync"),
                    ("auth_denied", "auth_denied"),
                    ("settings_change", "settings_change"),
                    ("degraded", "degraded"),
                    ("error", "error"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
