# Generated by Django 5.2.16 on 2026-07-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("events", "0002_sdkoperation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[("ui", "ui"), ("api", "api"), ("mcp", "mcp")],
                        max_length=8,
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("proposal", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("edited", "edited"),
                            ("rejected", "rejected"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commit_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("retries", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeds",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "sdk_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeds",
                        to="events.sdkoperation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="feeds_feed_status_f49a64_idx",
                    )
                ],
            },
        ),
    ]
