# Generated by Django 5.2.16 on 2026-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="decision_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feed",
            name="proposal_edited",
            field=models.BooleanField(default=False),
        ),
    ]
