# Generated by Django 5.2.16 on 2026-07-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_feed_decision_note_feed_proposal_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approving", "approving"),
                    ("approved", "approved"),
                    ("edited", "edited"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="pending",
                max_length=12,
            ),
        ),
    ]
