# Generated by Django 5.2.16 on 2026-07-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='extract_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
