# Generated by Django 5.2.16 on 2026-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0004_feed_extract_queued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="approve_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
