# Generated by Django 5.2.16 on 2026-08-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="URLMCPToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("prefix", models.CharField(db_index=True, max_length=24)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("last_4", models.CharField(max_length=4)),
                (
                    "max_visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("agents-only", "agents-only"),
                            ("private", "private"),
                        ],
                        default="public",
                        max_length=16,
                    ),
                ),
                ("rate_limit_per_min", models.PositiveIntegerField(default=60)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_mcp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "url_mcp_tokens_token",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="url_mcp_tok_user_id_d93bc8_idx",
                    )
                ],
            },
        ),
    ]
