# Generated by Django 5.2.13 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.BigIntegerField(
                        help_text="The user this row is scoped under. Anonymous requests skip idempotency entirely."
                    ),
                ),
                ("request_method", models.CharField(max_length=8)),
                ("request_path", models.CharField(max_length=512)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.BinaryField(blank=True, default=b"")),
                (
                    "response_content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_idempotent_request",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_idempo_created_3d7af4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "key"),
                        name="uniq_idempotent_request_user_key",
                    )
                ],
            },
        ),
    ]
