# Generated by Django 5.2.13 on 2026-05-01 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("prefix", models.CharField(db_index=True, max_length=20)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("last_4", models.CharField(max_length=4)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "plan_override",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "last_used_request_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_keys_api_key",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="api_keys_ap_user_id_7cfff2_idx",
                    )
                ],
            },
        ),
    ]
