# Generated by Django 5.2.16 on 2026-07-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("agents-only", "agents-only"),
                            ("private", "private"),
                        ],
                        default="public",
                        max_length=16,
                    ),
                ),
                ("rate_limit_per_min", models.PositiveIntegerField(default=60)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_profile",
                        to="api_keys.apikey",
                    ),
                ),
            ],
        ),
    ]
