# Generated by Django 5.2.16 on 2026-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("bootstrap", "bootstrap"),
                            ("manual", "manual"),
                            ("webhook", "webhook"),
                            ("beat", "beat"),
                            ("post-feed", "post-feed"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("commit_sha", models.CharField(blank=True, default="", max_length=64)),
                ("added", models.PositiveIntegerField(default=0)),
                ("changed", models.PositiveIntegerField(default=0)),
                ("removed", models.PositiveIntegerField(default=0)),
                ("drift_detected", models.BooleanField(default=False)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.CharField(max_length=200, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("identity", "identity"),
                            ("project", "project"),
                            ("take", "take"),
                            ("story", "story"),
                            ("lesson", "lesson"),
                            ("fact", "fact"),
                            ("catalog", "catalog"),
                            ("lens", "lens"),
                        ],
                        max_length=16,
                    ),
                ),
                ("path", models.CharField(max_length=300, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(blank=True, default="current", max_length=64),
                ),
                (
                    "superseded_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "public"),
                            ("agents-only", "agents-only"),
                            ("private", "private"),
                        ],
                        max_length=16,
                    ),
                ),
                ("topics", models.JSONField(blank=True, default=list)),
                ("projects", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, default="", max_length=300)),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("date", models.CharField(blank=True, default="", max_length=10)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "entities",
                "indexes": [
                    models.Index(
                        fields=["kind", "status"], name="brain_entit_kind_995c2e_idx"
                    ),
                    models.Index(
                        fields=["visibility"], name="brain_entit_visibil_1f8b5d_idx"
                    ),
                ],
            },
        ),
    ]
